version: '3'
services:
  monitoring_app:
    build:
      context: .
      dockerfile: Dockerfile_monitoring # Especificar la ruta del Dockerfile
    ports:
      - "5000:5000"
    command: python monitoring/logger.py  # Cambiar al archivo correcto dentro del contenedor

  api:
    container_name: mock-ecm-app
    build: ./app
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
